version: '3.8'

services:
  database:
    image: 'postgres:latest'

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: naval-battle
      POSTGRES_PASSWORD: naval-battle
      POSTGRES_DB: naval-battle
